### ISSUE TITLE
Server error with gerrit 2.14.7, oauth provider 2.14.6 and openjdk 8u151

### ISSUE THREAD

**Issue by 0x64616E69656C** [davido/gerrit-oauth-provider#104]
Hi,

I have a problem setting up gerrit (2.14.7) and OAuth2 provider 2.14.6 using openjdk-8-jre-headless 8u151 (9 and 10 don't work with gerrit) on debian testing.

I suspect this to be more of an openjdk issue rather than oauth-provider, however, I'm fresh out of ideas ;-)

My gerrit config:

<details>
 <summary>gerrit.cfg</summary>

```
[gerrit]
        basePath = git
        serverId = 123
        canonicalWebUrl = https://foo.bar.baz/
[database]
        type = h2
        database = /path/to/db/ReviewDB
[index]
        type = LUCENE
[auth]
        type = OpenID_SSO (tried OpenID and OAUTH too)
[receive]
        enableSignedPush = false
[sendemail]
        smtpServer = localhost
[container]
        user = gerrit
        javaHome = /usr/lib/jvm/java-8-openjdk-amd64/jre
[sshd]
        listenAddress = off
[httpd]
        listenUrl = proxy-http://127.0.0.1:8080/ (tried proxy-https too)
[cache]
        directory = cache
[plugin "gerrit-oauth-provider-google-oauth"]
        client-id = supersecret
        fix-legacy-user-id = false
```

</details>

When I try to sign in, I get redirected to Google's oauth login page, choose my account, and after redirection to my public facing gerrit URL I end up in a "Server error".

Gerrit's error log shows:
<details>
 <summary>error.log</summary>

```
[2018-03-15 09:25:19,018] [HTTP-69] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=foo&code=bar
org.scribe.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service.
        at org.scribe.model.Request.send(Request.java:70)
        at org.scribe.model.Request.send(Request.java:76)
        at com.googlesource.gerrit.plugins.oauth.OAuth20ServiceImpl.getAccessToken(OAuth20ServiceImpl.java:59)
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getAccessToken(GoogleOAuthService.java:202)
        at com.google.gerrit.httpd.auth.openid.OAuthSessionOverOpenID.login(OAuthSessionOverOpenID.java:100)
        at com.google.gerrit.httpd.auth.openid.OAuthWebFilterOverOpenID.doFilter(OAuthWebFilterOverOpenID.java:75)
        at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:73)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:111)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
        at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:133)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:135)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:72)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
        at org.scribe.model.Request.addBody(Request.java:136)
        at org.scribe.model.Request.doSend(Request.java:114)
        at org.scribe.model.Request.send(Request.java:66)
        ... 35 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
        at sun.security.validator.Validator.getInstance(Validator.java:179)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        ... 44 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
        ... 56 more
```

</details>

I'm not sure what "remote service" means here, whether it's my public facing gerrit url or Google's oauth API.

I suspected both Letsencrypt root CA (not an issue according to java keystore), the ECDSA P-384 cert (should not be an issue, I even added bouncycastle to the list of providers), so maybe you're able to hint me in the right direction.

Thank you very much in advance!

**Comment by davido** [comment]
What is in the error_log n gerrit?

**Comment by 0x64616E69656C** [comment]
Hi David,

the log is collapsed, just click on the "> error.log" link to show the full error log from gerrit.

**Comment by davido** [comment]
I've never seen such SSL connections issue.
That is not OAuth issue. obviously.
Yuo have connectivity issues. See for example:

https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

**Comment by 0x64616E69656C** [comment]
Yeah, I dug around a lot, most issues like the above came from misconfigured ca-certificates-java (not the case) or JCA issues.

Howecer JCA docs state that java 8 is perfectly fine handling TLS_ECDHE_ECDSA_* AEAD's (I even disabled TLS1.3 in case of handshake problems), ssllabs confirms both java7 and 8 can connect using SNI and letsencrypt's root CA is included in $JAVA_HOME/jre/lib/security/cacerts. :-/

I keep trying; closing this for now. If I find anything I'll let you know in case others have the same issue at some point.

**Comment by 0x64616E69656C** [comment]
Okay, I fiddled together a small tlstest class, and it turned out binfmts/jar was broken due to a previous openjdk-10 installation (wrong format). Now i works perfectly. :-)
