### ISSUE TITLE
How to delete external ids from Notesdb?

### ISSUE THREAD

**Issue by kellycampbell** [davido/gerrit-oauth-provider#107]
I ran into the same problem as #99 but this was after upgrading to gerrit 2.15, so the user data is now in Notesdb. I've read through most of the documentation for the accounts on Notesdb, and it looks like the best way to remove external ids is via the REST api. However, my account is one of the affected accounts, and I don't have a way to authenticate as the right user. Is there any easier way to fix this besides creating a new admin account  that uses password authentication via ssh?

**Comment by kellycampbell** [comment]
I figured out the following solution:

The only admin access I had was either directly on the filesystem, or ssh gerrit commands.

1. Set up an http user/password for the original admin user via ssh:

```
ssh <gerrit-hostnam> -p 29418 gerrit set-account --http-password <password> <orig acct id>
```

2. Check capabilities of that account (I'm using httpie locally on the gerrit server):

```
http --auth <user:pass> http://localhost:8080/a/accounts/self/capabilities
```

3. If `accessDatabase` is missing, then you have to add it by editing All-Projects/project.config. See https://groups.google.com/forum/#!topic/repo-discuss/x00M_NtWekA for how to do this.

4. Get the external id for the bad account:

```
http --auth <user:pass> http://localhost:8080/a/accounts/<bad acct id>/external.ids
```

5. Create a json request containing the result. e.g.:

```
[
  "google-oauth:<oauth identifier>"
]
```

6. Delete the external id:

```
http -v --auth <user:pass> POST http://localhost:8080/a/accounts/<bad acct id>/external.ids:delete  < delext.json
```

This should return `204 No Content`

**Comment by davido** [comment]
Thanks for figuring out and sharing. Probably would make sense to make it more visible, so that other folks could benefit from it.

**Comment by kellycampbell** [comment]
Would also be great if that legacy option was more prominent in release
notes or during the init script.

**Comment by davido** [comment]
/CC @davidpursehouse - Any comment on the call to make it more prominent in the release notes?

**Comment by kellycampbell** [comment]
Another idea: Is there any reason the legacy option shouldn't default to true? Or does it even need to be optional at all?

There is a chance to set it during the init, but I didn't know what it was and didn't look it up, so I just took the default.

**Comment by davido** [comment]
@kellycampbell Can you clarify what legacy option are you talking about?

**Comment by kellycampbell** [comment]
`fix-legacy-user-id`

**Comment by davido** [comment]
OK, I see your point. I will change it to `false` per default.

**Comment by kellycampbell** [comment]
I meant it should be `true` by default. Is it already that way? Something about my upgrade caused the problems seen in #99, which required all that manual rest api calls to fix for any user who tried to login after the upgrade and before I set the fix-legacy flag to true.

**Comment by davido** [comment]
Right now It's false by default:

```java
    if (configureGoogleOAuthProvider) {
      configureOAuth(googleOAuthProviderSection);
      googleOAuthProviderSection.string(FIX_LEGACY_USER_ID_QUESTION, FIX_LEGACY_USER_ID, "false");
    }
```

My concern to set it to true per default was the fact, that if the site was set up after 879bbae, this setting is not needed.

But yes, unfortunately, without this setting for the legacy sites, the new user ids are created on login attempt. That sucks, of course.

**Comment by jeoppy** [comment]
Hi kellycampbell & davido
I have followed your steps , (using gerrit 2.15.2 , and my user with "accessDatabase " perms) using curl 
where my json looks like :
```
[
  {
    "identity": "gerrit:zelda",
    "email_address": "zelda@company.com",
    "trusted": true,
    "can_delete": true
  },
  {
    "identity": "username:zelda",
    "trusted": true
  }
]
```
and my call looks like 
`curl  -u <my admin user>:<my pass> -X POST 'http://<my gerrit server ip>:8080/a/accounts/1000253/external.ids:delete' < delext.json`

**but** when I run the last step - the gerrit falls as follow : 

```
[2018-06-26 12:18:52,721] [HTTP-327] ERROR com.google.gerrit.httpd.restapi.RestApiServlet : Error in POST /a/accounts/1000253/external.ids:delete

java.lang.InstantiationException: Cannot make java.util.List<java.lang.String>
        at com.google.gerrit.httpd.restapi.RestApiServlet.createInstance(RestApiServlet.java:848)
        at com.google.gerrit.httpd.restapi.RestApiServlet.parseRequest(RestApiServlet.java:764)
        at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:404)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.google.gerrit.httpd.raw.StaticModule$PolyGerritFilter.doFilter(StaticModule.java:451)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.GetUserFilter.doFilter(GetUserFilter.java:100)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.RequireIdentifiedUserFilter.doFilter(RequireIdentifiedUserFilter.java:50)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:69)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.ProjectBasicAuthFilter.doFilter(ProjectBasicAuthFilter.java:100)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:133)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:135)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:69)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)

```
Do you have any idea as where this is coming from , 
or how to fix a workaround ?

**Comment by davido** [comment]
I would suggest to file an issue upstream, as this is not plugin related: https://bugs.chromium.org/p/gerrit/issues/entry .

**Comment by dpursehouse** [comment]
A couple of guesses:

1. Try to pass the content type in the request, i.e. `--header "Content-Type: application/json"`

2. Try passing the input with `-d@delext.json` instead of piping it.

**Comment by jeoppy** [comment]
thanks dpursehouse , did that - and the error of the gerrit stopped 
so now i have narrowed the issue just to 
> Invalid application/json in request

meaning , 
my json file is : 
```
[
  {
    "identity": "gerrit:zelda",
    "email_address": "zelda@company.com",
    "trusted": true,
    "can_delete": true
  },
  {
    "identity": "username:zelda",
    "trusted": true
  }
]
```
i call it with  : 
`curl -u user:pass -H "Content-Type: application/json; charset=UTF-8" -H "Accept: application/json" -d @./delext.json -X POST 'http://gerrit_server:8080/a/accounts/1000253/external.ids:delete'`

and since i get the json is invalid - i wonder if the info inside is what the rest needs ... or is it something else .
in sense of "validity" i have tested it with few json parsers  - and it is valid ...

**Comment by dpursehouse** [comment]
The content of the json looks different to the content in the example:

http://gerrit-documentation.storage.googleapis.com/Documentation/2.15/rest-api-accounts.html#delete-account-external-ids

**Comment by jeoppy** [comment]
dpursehouse  you are right 👍 
i took from the response of :
`curl  -u <user>:<pass> -X GET 'http://gerrit-server:8080/a/accounts/1000253/external.ids'`
only the value part of 

> "identity": "gerrit:zelda",

and placed it as follow to the json 
```
[
 "gerrit:zelda"
]
```

and it worked  and got deleted :)

**Comment by dpursehouse** [comment]
@davido can this be closed?
