### ISSUE TITLE
A new setup with gerrit and keycloak

### ISSUE THREAD

**Issue by mail2ganeshcse** [davido/gerrit-oauth-provider#121]
Hi davido,

i have done a new setup with gerrit oauth with key cloak, all the configuration between gerrit and keycloak has been done, when i click on gerrit sign in it redireccts to keycloak and after login with keycloak credential it redirects but says server error, when i see the log it i am getting below error.

[2019-02-26 18:38:36,063] [HTTP-97] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=W6B5p495kGemuhMJd_JjRdb2P5fOcnWm5cgRHfc9zbQ&session_state=320f5d04-867a-46e1-b37f-c0cc6ab023fe&code=f8450f17-8d7f-4abd-a199-b1a8d66cbe52.320f5d04-867a-46e1-b37f-c0cc6ab023fe.5f9d90e9-a456-41f8-b45b-6ea7222bcacd
java.lang.NoClassDefFoundError: com/google/gerrit/json/OutputFormat
        at com.googlesource.gerrit.plugins.oauth.KeycloakOAuthService.getUserInfo(KeycloakOAuthService.java:82)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:106)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:105)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:121)
        at com.google.gerrit.httpd.GwtCacheControlFilter.doFilter(GwtCacheControlFilter.java:72)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:133)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:135)
        at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:69)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.gerrit.json.OutputFormat
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 39 more

**Comment by davido** [comment]
> java.lang.NoClassDefFoundError: com/google/gerrit/json/OutputFormat

You have a mismatch with gerrit version and plugin version. It seems that you have built the plugin from master. You need earlier plgugin version, without this commit: [1].

* [1]

**Comment by mail2ganeshcse** [comment]
Yes it's resolved but after the sso with open id.. how can I create administrator account in gerrit since sai doesn't follow those access rules.m could pls explain due to this i am unable to create project or delete or access creation not able to do

**Comment by davido** [comment]
What gerrit version are you running?

Admin user privileges has nothing to do with this plugin. Very first user created in gerrit gets admin right. You could also add admin right manually if you have access to gerrit backends, but this depends on what version are you running and whether or not you are using NoteDb or ReviewDb.

**Comment by mail2ganeshcse** [comment]
Hi davido, i am using the 2.16.5 version, and H2 DB, the problem is i am creating the username and passwords on Keycloak and able to redirect login successfully but how to deal or add the created users with administrators group or Non-Interactive Users permissions groups. by default it just add on regiestered user group alone.

**Comment by davido** [comment]
The very first user created in gerrit is admin user. Just login in Gerrit with the very first created user, and this user is admin.

I don't fully understand your question.

Again, Set up a Gerrit site from scratch with Keycloak. Login with the first user. This user is admin.
