### ISSUE TITLE
oauth+ldap : groups and gitBasicAuth

### ISSUE THREAD

**Issue by mildis** [davido/gerrit-oauth-provider#122]
Hi,

I currently use ldap for our gerrit setup : both for gitBasicAuth and groups permissions.

Does the oauth plugin can request groups claim ?
If not, is LDAP leveraged to get the user's memberships ?
Can oauth be used for the web front-end but LDAP for gitBasicAuth ?

Thanks

**Comment by davido** [comment]
//CC @lucamilanesio.

**Comment by lucamilanesio** [comment]
In theory yes, just use HTTP_LDAP right?

**Comment by mildis** [comment]
My initial tries with 2.16.1 and 2.16.2 resulted in an exception thrown by the oauth plugin.
I’ll try again with 2.16.6 and an updated version of the plugin.

What about the group thing ?

**Comment by davido** [comment]
What exception?

**Comment by mildis** [comment]
With  `auth.type=OAUTH` and `auth.gitBasicAuthPolicy=HTTP_LDAP`, startup failed with 
`Caused by: java.lang.IllegalStateException: use auth.gitBasicAuthPolicy HTTP_LDAP only with auth.type LDAP or LDAP_BIND
	at com.google.gerrit.server.config.AuthConfig.<init>(AuthConfig.java:102)
	at com.google.gerrit.server.config.AuthConfig$$FastClassByGuice$$6973e1c8.newInstance(<generated>)`


with `auth.type=OAUTH` and `auth.gitBasicAuthPolicy=LDAP`, startup is OK, web interface is accessed over OAUTH but git clone failed with
`[2019-02-28 12:12:45,846] [HTTP-106] WARN  com.google.gerrit.httpd.ProjectBasicAuthFilter : Authentication from 127.0.0.1 failed for johndoe
com.google.gerrit.server.account.AccountException: Cannot authenticate
	at com.google.gerrit.server.auth.oauth.OAuthRealm.authenticate(OAuthRealm.java:85)
	at com.google.gerrit.server.account.AccountManager.authenticate(AccountManager.java:131)
	at com.google.gerrit.httpd.ProjectBasicAuthFilter.verify(ProjectBasicAuthFilter.java:156)
	at com.google.gerrit.httpd.ProjectBasicAuthFilter.doFilter(ProjectBasicAuthFilter.java:99)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:57)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:69)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by lucamilanesio** [comment]
@mildis why don't you write to the [repo-discuss mailing list](https://groups.google.com/forum/#!forum/repo-discuss)?  You're going to have a much bigger audience than just @davido and me.

**Comment by mildis** [comment]
Done.

**Comment by davido** [comment]
As @lucamilanesio pointed out and as can be seen from the exception, this is currently not supported.
