### ISSUE TITLE
Unable to build plugin

### ISSUE THREAD

**Issue by silviuvulcan** [davido/gerrit-oauth-provider#15]
Hi,

Any ideea why I'm not able to build it? I'm getting the following error:

```bash
# buck build plugin
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...0.8s (4/18 JOBS)
 |=> //lib/commons:codec__download_src...  0.2s (running genrule[0.2s])
 |=> //lib/gerrit:plugin-api__download_bin...  0.2s (running genrule[0.2s])
 |=> //lib:gson__download_bin...  0.0s (running genrule[0.0s])
 |=> //lib:gson__download_src...  0.0s (running genrule[0.0s])
 |=> //lib/commons:codec__download_bin...  0.2s (running genrule[0.2s])
Traceback (most recent call last):
  File "/usr/local/src/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 223, in execute
    self.execute_entry(entry_point, args)
  File "/usr/local/src/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 271, in execute_entry
    runner(entry_point)
  File "/usr/local/src/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 288, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/src/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/bucklets/tools/download_file.py", line 174, in <module>
  File "/usr/lib64/python2.7/subprocess.py", line 537, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:
genrule
[root@zac1d0153l gerrit-oauth-provider]# 
```

Thanks

**Comment by silviuvulcan** [comment]
Sorry, fixed it. Apparently I had to do:

    yum groupinstall 'Development Tools'

It would have been nice if the build process actually mentioned the tool it was missing like in the good old days :)

**Comment by prelegalwonder** [comment]
Is there a way to identify the missing components? I've tried:
> buck build -v 10 plugin 

and I get:
```BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:
(cd /root/gerrit-oauth-provider/buck-out/gen/lib/commons/codec__download_bin__srcs && OUT=/root/gerrit-oauth-provider/buck-out/gen/lib/commons/codec/commons-codec-1.4.jar /bin/bash -e -c '/root/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex -o $OUT -u MAVEN_CENTRAL:/commons-codec/commons-codec/1.4/commons-codec-1.4.jar -v 4216af16d38465bbab0f3dff8efa14204f7a399a -x META-INF/LICENSE.txt -x META-INF/NOTICE.txt')```

I've noticed that /root/gerrit-oauth-provider/buck-out/gen/lib/commons/codec/commons-codec-1.4.jar exists so I'm not sure where things are breaking down?

**Comment by davido** [comment]
Can you provide more context? Build mode (in tree standalone)? Gerrit and plugin version. It would also make sense to open new issue.

**Comment by Dawnthorn** [comment]
For me it turned out I just needed to have "zip" installed in the system. That error message is horrible, I had to use strace to figure out what it was trying to run.
