### ISSUE TITLE
Unable to build on CentOS 7

### ISSUE THREAD

**Issue by ntenev** [davido/gerrit-oauth-provider#16]
Hi,

I receive the following error, when I try to build the plugin:

```
 $ ~/install/buck/bin/buck build plugin
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...0.5s (14/18 JOBS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //lib/commons:codec__download_bin...  0.2s (running genrule[0.2s])
Traceback (most recent call last):
  File "/home/ntenev/install/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 223, in execute
    self.execute_entry(entry_point, args)
  File "/home/ntenev/install/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 271, in execute_entry
    runner(entry_point)
  File "/home/ntenev/install/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 288, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/usr/lib64/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ntenev/install/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/bucklets/tools/download_file.py", line 174, in <module>
  File "/usr/lib64/python2.7/subprocess.py", line 537, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:
genrule
```

Is there something I'm missing?

Regards!

**Comment by silviuvulcan** [comment]
Try 
```
yum groupinstall 'Development Tools'
```
That fixed it for me.

**Comment by ntenev** [comment]
Thanks, this works for me too!
