### ISSUE TITLE
Gerrit 3.4.1. oauth error

### ISSUE THREAD

**Issue by zhuyangyang-lingoace** [davido/gerrit-oauth-provider#161]
Gerrit version: 3.4.1
use  "gerrit-oauth-provider-azure-oauth" plugin
logs:
`
ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?code=0.AUkAqd5W_euXWEGgi7EbVw7MB4CRshF7kBJGja1UDpvDBD1JAMI.AQABAAIAAAD--DLA3VO7QrddgJg7WevrgakdOY3pRAu77vCLNLHmaszhKMYfkdFJP4gnROjwyhcQo2a937G4gQld2xIF_u0pW5cq0QzEDkx7HCi2y9pg761P4D2Bru4Norz1Z73qTj1-aoM_flH02fs2iTWSghRFn7HK_lJet7eub6wmxeUEZPpRHLQQ6QUJDrEjbCzIObEMxfzOKdDxhgx_ykyleFZeNT6xBfT8iC_l_CnYiDMsnCzZJ5cZqIri3uDCwDK2wWK4ySiC2YWPLDb8TMxg6vDXmptlR8rinvey4RPj9yJFXt56rJETCMSunpDnYpSbz-OanT5pZYB1aa75osGCtV35Ii3vdgOg2rK6tI1jHmYI5swsp0O_4kzkx-cKG6_Dt1LWbifkoCtkJuMm7I0BWFsxlz74cwOKOka-zzhkoIlt7AcR-Zm5qrAr0dXPGp6SlWdO74F1sIquluZ1gLupmwuoU1uTvHBIHIlke9tzSYJqvmspj0YmnblrkngqEnyhrIrC46KczjhJR08Pzm1HBlr0N52I14K2gG8YedhkRCVI49uJaiO97gMjWsGtf1VV_9yJoFZEruBxwiMj9hDsVbP-RM7zBcu9Z6QDuj_aTfEEO4RIStu7ElNvS2RS0JK1Z2CSRnyRFgB84B6pfPWMUHDvl0YIOAuEACi9JfrHE3avP9ZwHHfBhyCKsQpF8S_izDRRyDKS-SxfxGUXzNlRsUEDIAA&state=jsIehhneZa4HdZkxfClDSFWsZi3YEQznVW1Ltos1rSI%3d&session_state=a29a3ca7-4f5d-4239-84e3-13fe2302011c
java.lang.IllegalArgumentException: Illegal base64 character 2d
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:788)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:564)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:587)
        at com.googlesource.gerrit.plugins.oauth.AzureActiveDirectoryService.getTokenJson(AzureActiveDirectoryService.java:239)
        at com.googlesource.gerrit.plugins.oauth.AzureActiveDirectoryService.getUserInfo(AzureActiveDirectoryService.java:116)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:105)
        at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:72)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:120)
        at com.google.gerrit.httpd.SetThreadNameFilter.doFilter(SetThreadNameFilter.java:62)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:139)
        at com.google.gerrit.httpd.AllowRenderInFrameFilter.doFilter(AllowRenderInFrameFilter.java:56)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:135)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:141)
        at com.google.gerrit.httpd.RequestCleanupFilter.doFilter(RequestCleanupFilter.java:60)
        at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:92)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:64)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
`
@davido Hello  can you help me see ?

**Comment by davido** [comment]
> a29a3ca7-4f5d-4239-84e3-13fe2302011c java.lang.IllegalArgumentException: Illegal base64 character 2d

`2d`  is the character `-`, see: [1].

[1] https://stackoverflow.com/questions/41738065/failurejava-lang-illegalargumentexception-illegal-base64-when-decoding-jwt-tok

**Comment by zhuyangyang-lingoace** [comment]
@davido  Yes, but the oauth code is returned by the office365. We can't control

**Comment by davido** [comment]
Fixed in: [1].

[1] https://github.com/davido/gerrit-oauth-provider/issues/161
