### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by drahamim** [davido/gerrit-oauth-provider#23]
Not sure why this is happening. My build is failing and I'm not sure if it is buck or this. 

Here is the output when running buck build plugin

Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...1.3s (4/18 JOBS)
 |=> //lib/commons:codec__download_bin...  0.2s (running genrule[0.2s])
Traceback (most recent call last):
  File "/root/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 223, in execute
    self.execute_entry(entry_point, args)
  File "/root/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 271, in execute_entry
    runner(entry_point)
  File "/root/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 288, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/bucklets/tools/download_file.py", line 174, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 506, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:
genrule

**Comment by davido** [comment]
Have you looked at: #16:

```
yum groupinstall 'Development Tools'
```

**Comment by drahamim** [comment]
I was building on an ubuntu box. We have now changed to LDAP auth and no longer need the plugin.
