### ISSUE TITLE
Buck build plugin error commons:codec

### ISSUE THREAD

**Issue by lyhoanglong** [davido/gerrit-oauth-provider#26]
I had error log when run command line 

```
buck build plugin
```

this is error log: 

```
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...7.1s (14/18 JOBS)
 |=> IDLE
 |=> //lib/commons:codec__download_bin...  6.7s (running genrule[6.6s])
Download http://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
Traceback (most recent call last):
  File "/home/gerrit/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 223, in execute
    self.execute_entry(entry_point, args)
  File "/home/gerrit/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 271, in execute_entry
    runner(entry_point)
  File "/home/gerrit/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/.bootstrap/_twitter_common_python/pex.py", line 288, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gerrit/gerrit-oauth-provider/buck-out/bin/bucklets/tools/download_file.pex/bucklets/tools/download_file.py", line 174, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
BUILD FAILED: //lib/commons:codec__download_bin failed with exit code 1:
genrule
```

any suggestion for this issues?

**Comment by davido** [comment]
`download_file.py` bucklet makes use of `curl`. Make sure it's installed on your machine.

**Comment by davido** [comment]
On Fedora it can be installed with:

```
  yum groupinstall 'Development Tools'
```

**Comment by lyhoanglong** [comment]
@davido: I already installed curl. After buck show error missing curl, I install curl and this bug show up.

**Comment by davido** [comment]
OK, how about to install `zip`: [1]?

[1] https://github.com/davido/bucklets/blob/master/tools/download_file.py#L174
