### ISSUE TITLE
when I open settings/group-memberships, 500 Server Error

### ISSUE THREAD

**Issue by HackerOO7** [davido/gerrit-oauth-provider#31]
I updgrae from old gerrit version to gerrit-2.11, download from gerrit official website. The plugin download from release page.
 
My gerrit use Hybrid OpenID+OAuth method, and also set `trustedOpenID=^.*$`, it works. But when I open settings/group-memberships, the server 500 error.

the error log:

[2015-04-22 18:36:29,930] WARN  org.eclipse.jetty.servlet.ServletHandler : Error for /accounts/self/groups
java.lang.AbstractMethodError
	at com.google.gerrit.server.account.UniversalGroupBackend.isVisibleToAll(UniversalGroupBackend.java:193)
	at com.google.gerrit.server.account.GroupControl.isVisible(GroupControl.java:135)
	at com.google.gerrit.server.account.GetGroups.apply(GetGroups.java:54)
	at com.google.gerrit.server.account.GetGroups.apply(GetGroups.java:31)
	at com.google.gerrit.httpd.restapi.RestApiServlet.service(RestApiServlet.java:324)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:279)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:269)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:180)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.gerrit.httpd.GetUserFilter.doFilter(GetUserFilter.java:82)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:117)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:57)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:722)

**Comment by davido** [comment]
Can you try it with old OpenID account? And de-install the plugin. Does it work? What did you change, beside upgrade? JVM version?

**Comment by HackerOO7** [comment]
I just test it, with old OpenID the problem is always whether or not set up `trustedOpenID`. And re-install the plugin not work. I didn't change anything,  just upgrage from 2.8 to 2.9 2.10 and to latest verison. The java version is openjdk7 amd64.
