### ISSUE TITLE
Incorrect redirect link after login

### ISSUE THREAD

**Issue by kvdb** [davido/gerrit-oauth-provider#6]
I am currently using both gerrit.war and gerrit-oauth-provider plugin that you have released on Github. I have configured the plugin to only use Google OAuth provider. I'm authenticated correctly, however, the redirect back to the Gerrit website is incorrect. I end up on a 404:

    https://my.server.com/login/#/q/status:open
instead of:

    https://my.server.com/gerrit/#/q/status:open

Did I miss a setting? Or could it be a bug in this plugin?

Gerrit is hosted at: https://my.server.com/gerrit
The client id redirect is configured as: https://my.server.com/gerrit/oauth

**Comment by davido** [comment]
What is the valus of `gerrit.canonicalWebUrl`?

**Comment by kvdb** [comment]
That's:

    canonicalWebUrl = https://my.server.com/gerrit/

**Comment by davido** [comment]
OK, I misread your bug report. You are correctly authenticated and all is fine, beside the very first redirect?

**Comment by kvdb** [comment]
That's indeed the problem I'm having.
After a successful authentication, I need to manually browse to the right URL, in my case: https://my.server.com/gerrit/#/q/status:open
Then I can work in Gerrit as an authenticated user.

**Comment by davido** [comment]
Should be fixed in: [1]. Can you build gerrit and test it? Or should I build it and upload `release.war` at some place?

[1] https://gerrit-review.googlesource.com/67041

**Comment by kvdb** [comment]
If you're willing to build a new .war (both Gerrit and the plugin), I'd be happy to test it.

**Comment by davido** [comment]
Patched gerrit is here: [1]. The plugin was unchanged, compared to the last release 0.2: [2].

[1] http://ostrovsky.org/gerrit/gerrit-v2.10.2-18-g0ffaf73.war
[2] https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2

**Comment by kvdb** [comment]
It might be that it's still early here and I should grab another coffee first, but upgrading as I usually do:

    java -jar /usr/share/gerrit/gerrit-v2.10.2-18-g0ffaf73.war -d /usr/share/gerrit/

Resulted in:

    fatal: unknown command -d
          (no com.google.gerrit.pgm.-d)

Did the upgrade process change?

**Comment by davido** [comment]
Proably somehing went wrong during the build? investigating...

**Comment by davido** [comment]
I think, that the right command is:

```
$ java -jar  buck-out/gen/gerrit.war init -d ../test_xxx_zzz_yyy

*** Gerrit Code Review 2.10.2-18-g0ffaf73
*** 

Create '/home/davido/projects/test_xxx_zzz_yyy' [Y/n]?

[...]
```

**Comment by kvdb** [comment]
Ah, the 'init' was missing indeed.
Unfortunately, it didn't work yet. Hitting 'login' gave me this error:

[2015-04-13 09:30:04,041] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /gerrit/login/%23%2Fq%2Fstatus%3Aopen
	java.lang.AbstractMethodError: com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getAuthorizationUrl()Ljava/lang/String;
		at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:117)
		at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:119)
		at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
		at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:113)
		at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:68)
		at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
		at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:57)
		at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
		at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
		at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
		at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
		at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
		at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
		at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
		at org.eclipse.jetty.server.Server.handle(Server.java:461)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
		at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
		at java.lang.Thread.run(Thread.java:745)

As far as I could see, it didn't even redirect me to the Google auth page.

**Comment by davido** [comment]
Have you replaced the plugin with the new version from release 0.2?

**Comment by kvdb** [comment]
Ah, that seems to be it. It works as expected now. Thanks!

**Comment by davido** [comment]
Thanks for testing.
