### ISSUE TITLE
Failure to build on ubuntu.. 

### ISSUE THREAD

**Issue by pikeview** [davido/gerrit-oauth-provider#60]
I am trying to get gerrit run on ubuntu under virtual box, to support github & google login.
tried to build this plugin after cloning buck and oath provider. 

buck got built fine. But oauth-provider build failed

No idea what soever about the error and therefore unable to provide more details than the error stack..

gerrit2@quadpact:/opt/gerrit-tools/gerrit-oauth-provider$ echo $PATH
/opt/jdk1.8.0_102/jre/bin:/opt/jdk1.8.0_102/bin:/opt/apache-maven-3.3.9/bin:/opt/apache-ant-1.9.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

    me@localhost:/opt/gerrit-tools/gerrit-oauth-provider$ ../buck/bin/buck build plugin
    ::: '.nobuckcheck' file is present. Not updating buck.
    Not using buckd because watchman isn't installed.
    [+] PARSING BUCK FILES...1.7s
    BUILD FAILED: Parse error for build file /opt/gerrit-tools/gerrit-oauth-provider/BUCK:   File "/opt/gerrit-tools/gerrit-oauth-provider/buck-out/tmp/buck_run.yAJgHL/buck_python_program3965557948758093934/buck.py", line 1239, in process_with_diagnostics
    values = build_file_processor.process(build_file.rstrip(), diagnostics=diagnostics)
 
    File "/opt/gerrit-tools/gerrit-oauth-provider/buck-out/tmp/buck_run.yAJgHL/buck_python_program3965557948758093934/buck.py", line 1162, in process
    implicit_includes=self._implicit_includes)

    File "/opt/gerrit-tools/gerrit-oauth-provider/buck-out/tmp/buck_run.yAJgHL/buck_python_program3965557948758093934/buck.py", line 1101, in _process_build_file
    implicit_includes=implicit_includes)

    File "/opt/gerrit-tools/gerrit-oauth-provider/buck-out/tmp/buck_run.yAJgHL/buck_python_program3965557948758093934/buck.py", line 1023, in _process
    exec(code, module.__dict__)

    File "/opt/gerrit-tools/gerrit-oauth-provider/BUCK", line 36, in <module>
    local_license = True,
    File "/opt/gerrit-tools/gerrit-oauth-provider/bucklets/maven_jar.bucklet", line 116, in maven_jar
    out = binjar,
    File "/opt/gerrit-tools/gerrit-oauth-provider/buck-out/tmp/buck_run.yAJgHL/buck_python_program3965557948758093934/buck.py", line 139, in invoke
    return self.func(*args, **updated_kwargs)

    TypeError: genrule() got an unexpected keyword argument 'deps'

**Comment by davido** [comment]
```
::: '.nobuckcheck' file is present. Not updating buck.
```

is worrying. Build files must match the build tool version. Try remove it, Buck would update itself to the version mention in Bucklets.

If all other options fail, you could pull binary for this plugin either fom the release page: [1].

[1] https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.11.3

**Comment by davido** [comment]
Oh, i just realized, that Bucklets submodule wasn't updated for a while. So i fixed it, bumped plugin API version and even created new release: [1]. So try to pull (recursively) and build again.

[1] https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.12.4

**Comment by pikeview** [comment]
Hi David, thanks for the quick response.

I recloned the repo and also removed .nobuckcheck. Still build is failing

OSError: [Errno 2] No such file or directory


gerrit2:/opt/gerrit-tools/gerrit-oauth-provider$ ../buck/bin/buck build plugin
Buck is at b656a9033684917f7de4cf807b1cebabc701ac64, but should be e64a2e2ada022f81e42be750b774024469551398.
Buck is updating itself. To disable this, add a '.nobuckcheck'
file to your project root. In general, you should only disable
this if you are developing Buck.
Buck does not appear to have been built -- building Buck!
All done, continuing with build.
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.3s [100%]
[+] DOWNLOADING... (0.00 B/S, TOTAL: 0.00 B, 0 Artifacts)
[+] BUILDING...3.8s [20%] (8/24 JOBS, 8 UPDATED, 29.2% CACHE MISS)
 |=> //lib/commons:codec__download_bin...  0.2s (running genrule[0.2s])
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 320, in execute
  File ".bootstrap/_pex/pex.py", line 253, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 285, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 363, in _execute
  File ".bootstrap/_pex/pex.py", line 421, in execute_entry
  File ".bootstrap/_pex/pex.py", line 426, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bucklets/tools/download_file.py", line 198, in <module>
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by davido** [comment]
> File "bucklets/tools/download_file.py", line 198, in 

Given that this line is:

```
  check_call(['zip', '-d', args.o] + exclude)
```

installing `zip` on your system wouldn't hurt.

**Comment by pikeview** [comment]
oh such stupid error. I did not suspect such basic tool as zip would be missing in the default ubuntu  build. (I am running server inside my virtual box). Thanks for pointing it out. The build went fine after I installed zip. Proceeding to configure it. Hopefully I will not face any new issues. 

Thanks a lot.
