### ISSUE TITLE
Updated to Gerrit 2.13.1 - NullPointerException when trying to use Google OAuth

### ISSUE THREAD

**Issue by westhusing** [davido/gerrit-oauth-provider#63]
I upgraded my Gerrit instance to 2.13.1 from 2.12.4.

After upgrading, OAuth (Google) is not working anymore.  Here is the exception that I am receiving when trying to login:

```
[2016-09-23 21:20:16,968] [HTTP-92] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=xgYNogCwihbbktYmV-u67YupTcYruWithQL_xxL94zw&code=4/bzXBCiXF1Q62H-jNMHzFQuEbC0qOPL1h8-PfklyGbnk
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
        at com.google.gerrit.server.auth.oauth.OAuthTokenCache.put(OAuthTokenCache.java:80)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
        at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:60)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by davido** [comment]
It happens, when username is null:

```
public void put(OAuthUserInfo user, OAuthToken accessToken) {
    cache.put(checkNotNull(user.getUserName()),
        encrypt(checkNotNull(accessToken)));
  }
```

**Comment by davido** [comment]
This should be tracked in Gerrit issue tracker, as it's Gerrit core issue: [1].

**Comment by davido** [comment]
FWIW: If you need emergency fix for that, it's safe to revert the whole OAuth Token Cache series (that introduced the breakage):

```
commit 361adfac62ad3d2ef3c921430506724050930be9
Author: John Doe <john@doe.org>
Date:   Sat Sep 24 13:51:20 2016 +0200

    Revert "Cache for OAuth access tokens"
    
    This reverts commit 524faceb97b4b2e3fd4cde0e646e50e58e752704.

commit 99ab4fbecbc3a4b38f992578c23344a309f7f969
Author: John Doe <john@doe.org>
Date:   Sat Sep 24 13:51:07 2016 +0200

    Revert "REST API for retrieving OAuth access tokens"
    
    This reverts commit e56acd6cca0e7d028f9f3e3be115d83d88cf285c.

commit 509cae14d6052e22e01976e395f55e81cc926d25
Author: John Doe <john@doe.org>
Date:   Sat Sep 24 13:50:55 2016 +0200

    Revert "Settings screen for OAuth tokens"
    
    This reverts commit f698212ed01497919503bb8a0875f158b7b12718.
```

When these three commits are reverted on stable-2.13, OAuth extension point should work again.

**Comment by westhusing** [comment]
@davido, thank you for finding the cause of this issue.  I will try reverting those commits and building on my own.

**Comment by davido** [comment]
@westhusing I just uploaded an emergency fix with mention reverts here: https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.13.1.

**Comment by powderluv** [comment]
I still hit the same "server error" issue with 2.13.1 with the emergency release. Im unable to locate the logs listed above in my logs/error* though. 

I tried both building and using the version you uploaded.

**Comment by davido** [comment]
@powderluv Thanks for letting us know that emergency patch fixed the problem.

**Comment by ambakshi** [comment]
I'm seeing this on a 2.12 installation and haven't upgraded/changed anything in months. Was working perfectly fine until a day ago when it started breaking for some users. If you're still logged it it's ok, but once you log out, you can't get back in.

**Comment by davido** [comment]
@ambakshi Different problem: #65 different fix. Just deploy the plugin version from the 2.13.1 release.

**Comment by ambakshi** [comment]
@davido Thanks! That totally worked and I understand the underlying problem now.
