### ISSUE TITLE
Suddenly getting Google OAuth failures for all users

### ISSUE THREAD

**Issue by jpitt42** [davido/gerrit-oauth-provider#66]
This started happening this afternoon to all users of our Gerrit instance.  Users just get a simple page with "Server Error" when trying to sign in with Google.  We haven't changed anything in many weeks, and it was fine before.

We're using Gerrit 2.12.4 with the following plugin:

https://gerrit-ci.gerritforge.com/job/plugin-gerrit-oauth-provider-gh-master/lastSuccessfulBuild/artifact/buck-out/gen/plugins/gerrit-oauth-provider/gerrit-oauth-provider.jar from a few weeks ago.

`[2016-09-27 19:47:20,783] [HTTP-4686] WARN  org.eclipse.jetty.servlet.ServletHandler : /oauth
org.scribe.exceptions.OAuthException: Cannot extract an acces token. Response was: {
  "error" : "invalid_request",
  "error_description" : "OAuth 2 parameters can only have a single value: grant_type"
}
        at com.googlesource.gerrit.plugins.oauth.Google2Api$GoogleJsonTokenExtractor.extract(Google2Api.java:163)
        at com.googlesource.gerrit.plugins.oauth.Google2Api$GoogleOAuthService.getAccessToken(Google2Api.java:112)
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getAccessToken(GoogleOAuthService.java:221)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:98)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
`

Is anybody else seeing this?  I'm going to get to debugging, but I figured I'd ask if maybe others are seeing it, which might indicate something in the Google OAuth side that's changed.

**Comment by jpitt42** [comment]
Duplicate of https://github.com/davido/gerrit-oauth-provider/issues/64
