### ISSUE TITLE
Illegal request state

### ISSUE THREAD

**Issue by jdahlin** [davido/gerrit-oauth-provider#67]
Got an error this morning when it seems that Google changed their auth scheme, so I upgraded from 2.12 to 2.13.1 and downloaded the latest binary release of gerrit-oath-provider, but now I'm getting this error when trying to login:

> [2016-09-28 14:31:22,797] [HTTP-63] ERROR com.google.gerrit.httpd.auth.oauth.OAuthSession : Illegal request state 'CzRSQHus5m88cW9YoppnPoqitaBQBTCasVd6JF6woiI' on OAuthProtocol OAuthSession [token=null, user=null]

Then I recreated the client secret in the Google API Console and I get:

> [2016-09-28 14:37:15,128] [HTTP-65] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /review/oauth?state=2ouXGSsqPPLXTWJ51Okl7yVFjW-l4WL0CP02GCPQb-g&code=4/1uXUxVRe2sNdm_QFA1gUl_GomsSRmWguDnA1D4YVbwE&authuser=0&hd=sparkmeter.io&session_state=03d20fb1745f2b029d8e2fbd24103211c9ae5616..8461&prompt=none
> java.lang.NullPointerException
>         at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
>         at com.google.gerrit.server.auth.oauth.OAuthTokenCache.put(OAuthTokenCache.java:80)
>         at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
>         at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
>         at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
>         at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
>         at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:60)
>         at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
>         at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
>         at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
>         at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
>         at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>         at org.eclipse.jetty.server.Server.handle(Server.java:499)
>         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
>         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
>         at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
>         at java.lang.Thread.run(Thread.java:745)
> 

What am I doing wrong?

**Comment by jdahlin** [comment]
For what it's worth, relevant **gerrit.config** section:
> ...
> [auth]
> 	type = OAUTH
> 	openIdDomain = @_domain.tld_
> 	openIdSsoUrl = https://www.google.com/accounts/o8/id
> 	allowGoogleAccountUpgrade = true
> ...
> [plugin "gerrit-oauth-provider-google-oauth"]
>         client-id = _client-id from google api console_
> 	link-to-existing-openid-accounts = true
> 
> ...


And **secret.config**:
> ...
> [plugin "gerrit-oauth-provider-google-oauth"]
> 	client-secret = _client secret from google api console_
> ...

**Comment by jdahlin** [comment]
This is a duplicate of #66, using the provided gerrit.war worked.

**Comment by umesh936** [comment]
Hi, I did same configuration as you mentioned but still getting error
[2016-10-25 21:30:03,950] [HTTP-59] ERROR com.google.gerrit.httpd.auth.oauth.OAuthSession : Illegal request state 'IVq6E-av3vIIyzPLTfxV2b56NYfU8TJ8nPHXSVGVVR0' on OAuthProtocol OAuthSession [token=null, user=null]
There is one difference rather than secret.config, it is secure.config where i have added clietn secret.. It authenticate gmail well but on redirect back it shows not found.

I am on gerrit 2.13.2 with latest plugin available..

**Comment by davido** [comment]
Have you tried to add client secret in gerrit.config instead? I saw some reports, where the values in secure.config  were ignored.

**Comment by umesh936** [comment]
yes i did here is my  configuration, i belive secret was picking other wise google will not show that allow page to user. Problem start when it redirect from google login..
`[gerrit]
	basePath = git
	serverId = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	canonicalWebUrl = http://git.domain.in/
[database]
	type = mysql
	hostname = localhost
	database = reviewdb
	username = gerrit2
[index]
        type = LUCENE
[auth]
	type = OAUTH
	openIdDomain = @domain.tld
	openIdSsoUrl = https://www.google.com/accounts/o8/id
	allowGoogleAccountUpgrade = true

[receive]
	enableSignedPush = false
[sendemail]
        enable = true
        smtpServer = smtp.gmail.com
        smtpServerPort = 465
        smtpEncryption = SSL
        sslVerify = false
        smtpUser = jenkins@xxxxxxxxxx.in
        smtpPass = xxxxxxxxxx
        from = ${user} (Code Review) <gerrit@xxxxxxxxxx.in>
[container]
	user = gerrit2
	javaHome = /usr/lib/jvm/java-7-openjdk-amd64/jre
[sshd]
	listenAddress = *:29418
[httpd]
	listenUrl= proxy-https://*:8444/
[cache]
	directory = cache
[download]
        command = checkout
        command = cherry_pick
        command = pull
        command = format_patch
        scheme = ssh
        scheme = http
        scheme = anon_http
        scheme = anon_git
        scheme = repo_download

[plugin "gerrit-oauth-provider-google-oauth"]
	client-id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.googleusercontent.com
	client-secret = xxxxxxxxxxxxxxxxxxxxxxxxxn
	link-to-existing-openid-accounts = true
`

**Comment by umesh936** [comment]
do i have to move to any old  version ? my team is waiting for this to up.. Need some direction from here..

**Comment by davido** [comment]
Why are you setting this options:

```
openIdDomain = @domain.tld
openIdSsoUrl = https://www.google.com/accounts/o8/id
link-to-existing-openid-accounts = true
```

You are using `OAUTH` auth scheme, so they aren't related.

Can you provide more detals: did oauth-provider plugin even worked for you? Have you upgraded from older Gerit/plugin versions? Or are you trying to set it up for the first time?

Are you migrating your site from `OpenID`?

**Comment by umesh936** [comment]
Hi David thanks for this information. It is a fresh  installation, no migration from any old gerrit or auth scheme. I setup the gerrit in pat company with google login and it was working fine with 2.10 version. This time i started with latest version of gerrit and it failing after redirection. 
this is log trace in error 
[2016-10-27 08:18:43,904] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin reviewnotes, version v2.13.2
[2016-10-27 08:18:44,015] [main] INFO  com.google.gerrit.server.plugins.PluginLoader : Loaded plugin singleusergroup, version v2.13.2
[2016-10-27 08:18:44,020] [main] INFO  com.google.gerrit.server.change.ChangeCleanupRunner : Ignoring missing changeCleanup schedule configuration
[2016-10-27 08:18:44,075] [main] INFO  com.google.gerrit.sshd.SshDaemon : Started Gerrit SSHD-CORE-1.2.0 on *:29418
[2016-10-27 08:18:44,084] [main] INFO  org.eclipse.jetty.server.Server : jetty-9.2.14.v20151106
[2016-10-27 08:18:45,013] [main] INFO  org.eclipse.jetty.server.handler.ContextHandler : Started o.e.j.s.ServletContextHandler@612067b0{/,null,AVAILABLE}
[2016-10-27 08:18:45,020] [main] INFO  org.eclipse.jetty.server.ServerConnector : Started ServerConnector@55efbdc9{HTTP/1.1}{0.0.0.0:8444}
[2016-10-27 08:18:45,022] [main] INFO  org.eclipse.jetty.server.Server : Started @13507ms
[2016-10-27 08:18:45,023] [main] INFO  com.google.gerrit.pgm.Daemon : Gerrit Code Review 2.13.2 ready
[2016-10-27 08:19:39,253] [HTTP-60] ERROR com.google.gerrit.httpd.auth.oauth.OAuthSession : Illegal request state 'OoJ0mPV5GEgbOsWkztSs-ef3YKZGvAOksYZC-yygH5Q' on OAuthProtocol OAuthSession [token=null, user=null]

I can start with new installation also for now..i am trying to with same gerrit version

**Comment by davido** [comment]
So, i checked the code: We generate random state on session initialization:

```
this.state = generateRandomState();
````

Then we send it to OAuth provider:

```
esponse.sendRedirect(oauth.getAuthorizationUrl() +
        "&state=" + state);
```

And then we get it on the response from the provider and check that it matches:

```
private boolean checkState(ServletRequest request) {
    String s = Strings.nullToEmpty(request.getParameter("state"));
    if (!s.equals(state)) {
      log.error("Illegal request state '" + s + "' on OAuthProtocol " + this);
      return false;
    }
    return true;
  }
```

No clue, why it doesn't work for you.

**Comment by umesh936** [comment]
yes i get this url http://<mydomain>/oauth?state="--" but on page Not found is written... I am using open jdk , that can be issue ?

**Comment by umesh936** [comment]
Now i have moved to version 2.13.1

latest error is like org.eclipse.jetty.servlet.ServletHandler : /oauth
java.lang.NullPointerException
[2016-10-27 15:57:28,574] [HTTP-60] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=INYkHLuFxYbqZ2ER6eJ0H88rQB4giJIQm5WP1S7CJ2s&code=4/_9Ua9f1BSfnc89eMsCz-nCabg4aTsAToH5QxgQINT-E
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.google.gerrit.server.auth.oauth.OAuthTokenCache.put(OAuthTokenCache.java:80)
	at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:105)
	at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:60)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by davido** [comment]
You cannot use 2.13.1, OAuth extension point is broken there. You must use 2.13.2.

**Comment by umesh936** [comment]
aah finally got the issue... there was https mention in my proxy configuration in gerrit.config but i am not using ssl for now.. and yes i jumped back to 2.13.2 version.. its up and working now... thanks for your patience ans time

**Comment by davido** [comment]
Glad to hear it worked for you in the end.

**Comment by zygimantus** [comment]
@davido , @umesh936  I am getting the same error: 

> [2018-09-13 14:08:38,904] ERROR com.google.gerrit.httpd.auth.oauth.OAuthSession : Illegal request state 'QQeIyuyR_nt33V3V5LNVcX6jzXe6XZq77GxNEdMNdUk' on OAuthProtocol OAuthSession [token=null, user=null]

What does this error actually mean? Maybe it says that given state is not recognizable somehow by gerrit OAuth plugin? Is it possible to test if it is the case?

**Comment by davido** [comment]
@zygimantus Let's stay on another issue #109 related to CAS.
