### ISSUE TITLE
com.google.gerrit.server.account.AccountException: Cannot authenticate

### ISSUE THREAD

**Issue by farhan-mosaixsoft** [davido/gerrit-oauth-provider#70]
Hello,
I am trying to use github identities but unable to make this work if I set the [auth] type to oauth. (Exception in logs is listed below)
I get forwarded to github login screen and then redirected back to gerrit after login but end up with HTTP status "Forbidden" 
I am using the latest version [gerrit-v2.13.1-10-gbf8b34a.war] from:
https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.13.1
I have looked through the issues and the online posts and seems like this should work.
What am I missing??
Any pointers would be appreciated:
Thanks,
-Farhan.

Here is my gerrit.config:
------------------------------------------------------------------------------------------------------------------
[gerrit]
	basePath = git
	serverId = b2aab1fb-7016-4884-9685-b5b61ffcbad7
	canonicalWebUrl = http://<SERVER_IP>:8080/
[database]
	type = h2
	database = /home/gerrit2/gerrit_review/db/ReviewDB
[auth]
	type = OAUTH
[receive]
	enableSignedPush = false
[sendemail]
	smtpServer = localhost
[container]
	user = gerrit2
	javaHome = /usr/lib/jvm/java-8-oracle/jre
[sshd]
	listenAddress = *:29418
[httpd]
	listenUrl = http://*:8080/
[cache]
	directory = cache
[plugin "gerrit-oauth-provider-github-oauth"]
	client-id = <>
------------------------------------------------------------------------------------------------------------------

Exception in the logs:
-------------------------------------------------------------------------------------------------------------------
[HTTP-62] ERROR com.google.gerrit.httpd.auth.oauth.OAuthSession : Unable to authenticate user "com.google.gerrit.extensions.auth.oauth.OAuthUserInfo@dbb08ab"
com.google.gerrit.server.account.AccountException: Cannot authenticate
	at com.google.gerrit.server.auth.oauth.OAuthRealm.authenticate(OAuthRealm.java:89)
	at com.google.gerrit.server.account.AccountManager.authenticate(AccountManager.java:124)
	at com.google.gerrit.httpd.auth.oauth.OAuthSession.authenticateAndRedirect(OAuthSession.java:143)
	at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:104)
	at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:122)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequestMetricsFilter.doFilter(RequestMetricsFilter.java:60)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:138)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by farhan-mosaixsoft** [comment]
It seems that the issue is related to the first user login. If I switch to [auth] as openid and then first login using an openid, then subsequent logins using github oauth work, but for some reason the github users are not visible from the admin openid user. 
Any debugging pointers/help would be appreciated.
Thanks

**Comment by davido** [comment]
There was a regression in OAuth extension point that prevent authentication for OAuth provider (and users) that don't expose E-Mail address. It was fixed meantime and released. Upgrade Gerrit to 2.13.2 and it should just work.

**Comment by charles-augustin** [comment]
jh
