### ISSUE TITLE
Gerrit OAuth provider: OpenID 2.0 identifier mapping is discontinued

### ISSUE THREAD

**Issue by naiquevin** [davido/gerrit-oauth-provider#77]
Gerrit version: v2.10.2-18-gc6c5e0b-dirty
gerrit-oauth-provider version: v0.3 (patched with PR #65 )

Following errors can be seen in the error log 

```
[2017-01-11 06:43:52,801] WARN  org.eclipse.jetty.servlet.ServletHandler : /oauth
java.lang.NullPointerException
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.lookupClaimedIdentity(GoogleOAuthService.java:154)
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getUserInfo(GoogleOAuthService.java:123)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:94)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:123)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:113)
        at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:68)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:57)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
        at org.eclipse.jetty.server.Server.handle(Server.java:461)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
[2017-01-11 06:43:52,802] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=xxx&code=xxx&authuser=0&hd=xxx&session_state=xxx&prompt=none
java.lang.NullPointerException
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.lookupClaimedIdentity(GoogleOAuthService.java:154)
        at com.googlesource.gerrit.plugins.oauth.GoogleOAuthService.getUserInfo(GoogleOAuthService.java:123)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:94)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:123)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
        at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:113)
        at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:68)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
        at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:57)
        at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
        at org.eclipse.jetty.server.Server.handle(Server.java:461)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
```

What could be the issue? Is any one else also facing this?

**Comment by davido** [comment]
What is the ine GoogleOAuthService.java:154 in your patched code base?

**Comment by naiquevin** [comment]
@davido: This https://github.com/davido/gerrit-oauth-provider/blob/v0.3/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java#L154

**Comment by davido** [comment]
Oh, I see, then this should fix it:

```
 if (openidIdElement != null && !openidIdElement.isJsonNull()) {
```

right?

**Comment by davido** [comment]
Ah, I guess I have an idea what is going on here: Google discontinued legacy OpenID support in their OAuth 2 backend.

**Comment by davido** [comment]
Check this spec: https://developers.google.com/identity/protocols/OpenID2Migration, particularly, this statement:

  Note: Support for the OpenID 2.0 identifier mapping described above will remain in effect until January 1, 2017.

IOW, i would have to release new version of Google OAuth2 provider and drop legacy OpenID implementation.

**Comment by davido** [comment]
You could probably fix that by disabling now non working configuration option:

```
  Link to OpenID accounts? [true]: false
```

**Comment by naiquevin** [comment]
@davido Thanks. I will try disabling linking to OpenID accounts.

**Comment by naiquevin** [comment]
@davido It worked on setting`linkToExistingOpenIDAccounts` to false. Thanks for all the help 👍

**Comment by davido** [comment]
Thanks for letting us know ;-)

**Comment by davido** [comment]
Fixed with: https://github.com/davido/gerrit-oauth-provider/commit/98f1be93539ea88e9cbc60a513cf00de8d01cf27.
